window.COURSES = [
  {
    "title": "Computational Intelligence for Humanities",
    "course_number": "",
    "school": "",
    "units": [],
    "instructors": [],
    "description": "This course introduces substantial machine learning methods of particular relevance to humanistic scholarship. Areas covered include standard models for classification, regression, and topic modeling, before turning to the array of open-source pretrained deep neural models, and the common mechanisms for employing them. Students are expected to have a level of programming experience equivalent to that gained from AS.360.304, Gateway Computing, AS.250.205, or Harvard’s CS50 for Python. Students will come away with an understanding of the strengths and weaknesses of different machine learning models, the ability to discuss them in relation to human intelligence and to make informed decisions of when and how to employ them, and an array of related technical knowledge.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["machine-learning", "humanities",  "python",  "human-intelligence"]
  },
  {
    "title": "Introduction to Computational Methods for the Humanities",
    "course_number": "AS.360.305",
    "school": "",
    "units": [],
    "instructors": [],
    "description": "This course introduces basic computational techniques in the context of empirical humanistic scholarship. Topics covered include the command-line, basic Python programming, and experimental design. While illustrative examples are drawn from humanistic domains, the primary focus is on methods: those with specific domains in mind should be aware that such applied research is welcome and exciting, but will largely be their responsibility beyond the confines of the course. Students will come away with tangible understanding of how to cast simple humanistic questions as empirical hypotheses, ground and test these hypotheses computationally, and justify the choices made while doing so. No previous programming experience is required.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["humanities", "python",  "experimental-design", "hypothesis-testing", "empirical-research", "data-analysis"]
  },
  {
    "title": "Language, Media, and AI Lab (LAMA Lab)",
    "course_number": "AS.070.131",
    "school": "",
    "units": [],
    "instructors": ["MacLochlainn, Scott"],
    "description": "LAMA Lab is a space in which students and faculty address the different technologies of language and media. Encompassing in its approach and design, this lab emphasizes an up-close, ethnographic, and qualitative approach, and with an eye to AI and its influences and effects on media. With a particular attention to shifting technological developments, LAMA Lab is open-ended and exploratory in nature. Centered around reading groups, workshops, guest speakers, and experimentation with different interfaces and software, as well as providing small grants, this laboratory provides a space of convergence for those who are engaging in questions related to language, media, and AI. It is accessible to students and faculty at different stages of research, from planning to post-research analysis. This laboratory also provides a wider space for ethnographic engagements with language and media, from translation and oral history to audio and visual archives. For students enrolling for 1-credit course, the lab will meet throughout the semester, approximately every three weeks. Credit hours will be accrued through attendance to guest speakers, workshops and reading groups.",
    "credits": "1 (implied)",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["lab", "ethnography", "qualitative-methods",   "translation", "oral-history"]
  },
  {
    "title": "AI: Utopias, Dystopias, and Everything in Between",
    "course_number": "AS.070.302",
    "school": "",
    "units": [],
    "instructors": [],
    "description": "In this course, we will explore the social worlds of AI. Given how AI is and promises to be increasingly interwoven into multiple aspects of our lives, we will examine different ways of thinking and ethnographically engaging in these emergent technologies. We will think about how people are encountering and designing AI in different ways, from the ubiquity of AI slop on social media and ChatGPT to the predictive use of AI in healthcare, to the internal culture of start-ups. Throughout the semester, we will move between spaces of media, the uses of large language models and their relationship to the speaking subject, ethnographies on technology and labor rights, surveillance, and state and corporate uses of AI. We will also consider fundamental questions concerning the relationship between technology and life, the utopias of automation, the ethics of human exceptionalism, and the potential legal frameworks in which to situate and guardrail AI.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["ethnography", "social-media",  "healthcare", "startups", "labor-rights", "surveillance", "automation", "human-exceptionalism", "legal-frameworks", "technology-society"]
  },
  {
    "title": "Practical Mathematics for AI",
    "course_number": "AS.110.204",
    "school": "",
    "units": [],
    "instructors": ["Ali Yousuf, Muhammad"],
    "description": "This course provides a rigorous yet accessible introduction to the essential mathematical foundations underlying modern Artificial Intelligence (AI) and Deep Learning applications. The course emphasizes the practical application of linear algebra, probability, statistics, calculus, and optimization techniques in the design and understanding of machine learning systems. Students will explore how these core mathematical tools are used to build models for computer vision, regression, classification, clustering, and deep neural networks. Each topic is contextualized with real-world problems, Python Code, and bridging theory with implementation. The course is designed for students from diverse academic backgrounds who want to gain a solid foundation in mathematics for working with AI systems. Topics include: Vectors, matrices, and tensor operations; Calculus and gradient-based optimization for training neural networks; Probability theory and statistical inference in machine learning; Mathematical intuition behind computer vision, regression, classification, clustering, and deep neural networks with practical use cases.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["linear-algebra", "probability", "statistics", "calculus", "optimization", "gradient-descent", "deep-learning", "computer-vision", "classification", "clustering", "python", "math-foundations"]
  },
  {
    "title": "Philosophy and AI in Healthcare",
    "course_number": "AS.150.336",
    "school": "",
    "units": [],
    "instructors": ["Christy, Rooke"],
    "description": "This course provides an introduction to current, ongoing debates around the use of AI in healthcare, as well as relevant philosophical problems. No prior knowledge in AI, healthcare, or philosophy required.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["philosophy",  "healthcare", "ethics", "responsibility"]
  },
  {
    "title": "Directed Improvisation with AI",
    "course_number": "AS.190.644",
    "school": "",
    "units": [],
    "instructors": ["Ang, Yuen Yuen"],
    "description": "This exploratory PhD seminar invites students into the emerging space where human research practices and artificial intelligence begin to intersect. Framed by the concept of directed improvisation, the course treats the human researcher as a director—shaping the conditions and prompts under which AI, like a responsive actor, contributes to the creative process. AI is not approached as a shortcut, a threat, or mere tool, but as a partner in co-creation. The course covers the intellectual history of AI, contemporary debates, and practical applications of AI for research tasks. This is not a course with prepackaged answers. Our goal is to think and practice together, engaging in a range of novel questions that haven’t yet been fully named.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "PhD seminar (as described).",
    "keywords": ["phd-seminar", "research-practice", "human-ai-collaboration",  "creative-process", "ai-history", "methods", "improvisation"]
  },
  {
    "title": "AI and Democracy",
    "course_number": "AS.196.325",
    "school": "",
    "units": [],
    "instructors": ["Farrell, Henry"],
    "description": "How will the advent of AI affect democracy in the US and elsewhere? And how should democratic principles shape technologies such as AI? In this course, we will explore the potential consequences of technologies such as large language models for democratic culture and institutional stability. We will investigate whether we ought incorporate democratic values into the design of AI, to address problems such as bias and safety. We will discuss the new questions that arise as AI agents become active in society, and the consequences for employment. Finally, we will examine how or whether democracies ought govern AI and related technologies.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["democracy", "governance", "policy",  "bias", "safety",  "institutions",  "values"]
  },
  {
    "title": "SOUL: AI and Society - Navigating a Changing Landscape",
    "course_number": "AS.360.111",
    "school": "",
    "units": [],
    "instructors": ["Braley, Emily", "Puglionesi, Alicia G", "Tatarchenko, Ksenia", "Watters, Aliza"],
    "description": "Artificial Intelligence (AI) is rapidly shaping how we learn, work, and communicate—but understanding what AI is, how it works, and when it should be used requires more than technical knowledge. This 1-credit seminar invites students to explore AI through a humanities-informed lens, emphasizing historical context, conceptual inquiry, and critical reflection. Students will be introduced to how AI systems, such as machine learning models, are developed and trained, and will consider questions about intelligence, prediction, and human judgment. Through guided discussion, short readings, reflective writing, and low-stakes engagement with AI tools, students will examine different ways AI is used across academic, social, and professional settings. Using case studies drawn from areas such as mental health, deepfakes, social media, and recommendation systems, students will have the opportunity to critically analyze ethical concerns—including bias, privacy, environmental impact, accountability, and institutional power—aligned with their goals and interests. No prior experience with AI is required.",
    "credits": "1",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["ai", "society", "humanities", "history",  "ethics", "bias", "privacy", "recommendation-systems", "environmental-impact", "accountability"]
  },
  {
    "title": "Learning Sex and Gender: AI, Algorithms, Automatons",
    "course_number": "AS.363.367",
    "school": "",
    "units": [],
    "instructors": ["Islam, Heba Zainab"],
    "description": "This course explores the interactions between sex, gender, and cyber-technologies, old and new. How do the internet, smart devices, robots and generative AI shape sex and gender? In turn, how do discourses of sex and gender shape technologies? This seminar will help students answer these questions by introducing them to debates within feminist theory, the historical development of gendered and sexed technologies, the embedding of these technologies in our everyday life and the aesthetics and ethics of such technologies as seen in film and media. We will explore how AI, algorithms, and machines raise complex questions around the ethics, politics, and epistemologies of sex and gender. Through readings of key academic texts, films, and ethnographies, we will try to gain a full picture, through discussion, of what a gendered cyberscape looks like and how it might come to look otherwise. By understanding such technologies as instruments of power, we will analyze how this power is applied differentially across different marginalized groups and in different regional contexts. Further, we will consider how technologies enter our intimate spaces and reshape our desires and pleasures.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["sex", "gender", "feminist-theory", "cybertechnology", "robots", "film-and-media", "ethnography",  "ethics"]
  },
  {
    "title": "AI and the U.S. Intelligence Community",
    "course_number": "AS.473.630",
    "school": "",
    "units": [],
    "instructors": ["Johnston, Barney"],
    "description": "This course addresses what is AI, how it developed, and how it is used in the intelligence community for national defense. This course will prepare students to better understand this exciting technology and how best to apply it for current problems. It will delve into the immense promise and power, and serious pitfalls, of AI use. The course will investigate the history of the science behind AI, its current theory, different models of usage, how it is being used, and ethics and national policy. In particular, the course will focus considerable attention on AI as used in intelligence analysis. The course will also look to the future of human interface with AI.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["national-security", "intelligence-community", "intelligence-analysis", "ai-history", "ethics", "policy",  "human-ai-interface"]
  },
  {
    "title": "Storytelling with Data and AI",
    "course_number": "AS.491.705",
    "school": "",
    "units": [],
    "instructors": ["Gourgey, Bill"],
    "description": "Discover the power and impact of data-driven stories. Through case studies and hands-on experience, students will explore the art of sourcing, analyzing, and verifying data, and using AI reporting tools, while applying narrative skills to write compelling data-driven stories about science, medicine, and technology. Engage in discussions about the biases buried in data, the influence data has on our lives, the channels for mis- and disinformation, and the unique ways in which data storytelling can enhance reader engagement. Learn to work with three key aspects of data storytelling: sourcing the data, presenting the data (often called visualization), and writing narratives that unpack hidden messages. This writing elective opens with a 4-week introduction to data, including data sourcing, analysis, and verification, with user-friendly tools, that don’t require deep technical skills. Accompanying readings will focus on best practices in data journalism and using AI within the ethical bounds of journalism, with examples of compelling data-driven stories. In preparation for writing their own data-driven stories, students will examine case studies that demonstrate how data is collected, transformed, analyzed, and interpreted to forge engaging narratives and accompanying visuals. Following the case studies, students will share their data-driven stories and critique their classmates' work. By the end of the course, students can expect to have a solid foundation in data literacy and the ability to tell stories with data. Prerequisite: AS.491.658, AS.491.750, or permission of your academic advisor.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Prerequisites listed.",
    "keywords": ["data-journalism", "storytelling",  "visualization", "misinformation", "bias", "science-writing", "narrative"]
  },
  {
    "title": "Responsible AI",
    "course_number": "",
    "school": "",
    "units": [],
    "instructors": ["Agarwal, Ritu"],
    "description": "In light of the accelerating and ubiquitous impact of artificial intelligence (AI) on all sectors of the economy, the significance of responsible AI, i.e., systems that conform to principles of safety, equity, fairness, etc. is paramount. This course is crafted to equip business leaders, AI practitioners, and policymakers with an in-depth understanding of the ethical, safety, and governance issues associated with AI technologies. Topics include ethical frameworks in AI, AI safety, the current regulatory landscape and governance roles, sources of bias in AI, transparency and accountability in AI systems, and real-world case studies in the finance, healthcare, marketing, and management domain . Upon completion, students will have acquired the essential knowledge and skills to formulate organizational strategies that integrate responsibility throughout the AI development lifecycle.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["responsible-ai", "ai-safety", "fairness", "equity", "governance", "regulation", "bias", "transparency", "accountability", "business-strategy", "risk-management"]
  },
  {
    "title": "AI Development and Business Applications",
    "course_number": "",
    "school": "Carey Business School",
    "units": ["BU Information Systems"],
    "instructors": [],
    "description": "This course covers the foundations of Artificial Intelligence (AI) technologies with emphasis on their business application. It will cover models of machine learning and pattern optimizations. This course will enable the student to gain a fundamental understanding of the foundations and applications of different AI technologies, analysis of the required AI algorithms and machine Learning technologies, necessary to support different business applications. It will require basic uses and applications of an AI tool’s (IBM Watson, Python, or R,), however, it does include teaching software coding.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Course number/instructor not provided in this entry.",
    "keywords": ["business-applications", "python", "r", "coding"]
  },
  {
    "title": "AI Development and Business Applications",
    "course_number": "BU.330.750",
    "school": "Carey Business School",
    "units": ["BU Information Systems"],
    "instructors": ["Xu, Minghong"],
    "description": "This comprehensive course is designed to immerse students in the dynamic fields of generative AI. By exploring both the theoretical underpinnings and practical applications, students will gain an in-depth understanding of the most advanced AI models and their impact across various business sectors. Knowledge of deep learning is recommended but not required. Topics include encoder-decoder architectures, generative adversarial networks (GANs), text and natural language generation using transformer models, as well as cutting-edge image generation models like Stable Diffusion, Midjourney, DALL-E, and innovative video generation models like W.A.L.T. The course adopts a hands-on, learning-by-doing approach. Students will utilize Python packages such as scikit-learn, Keras, TensorFlow, and PyTorch. The focus is on fostering awareness of these technologies, building some level of familiarity through assignments, and developing strategic thinking regarding their application in business.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": [ "business-strategy"]
  },
  {
    "title": "AI in Marketing",
    "course_number": "BU.420.750",
    "school": "Carey Business School",
    "units": ["BU Marketing"],
    "instructors": ["Godes, David"],
    "description": "This course prepares students to thrive in an AI-driven marketing world. We begin with the proposition that AI is transforming fundamentally the way organizations of all types acquire, nurture, retain and monetize customer relationships. After an introductory session providing the necessary basic statistical and contextual background, the course proceeds through a range of applications via which students will develop an understanding of both “what” these technologies are able to do and “how” marketers can benefit from them in practice. We will cover both predictive and generative models with specific applications drawn from predicting customer churn, generalizing insights from pilot tests to acquisition at-scale, mining customer feedback for new product ideas, optimizing content for search-engine optimization (SEO), writing marketing copy, and the possibility of using LLMs as a substitute for costly market research. Neither prior machine learning knowledge nor significant coding experience are required (though they are of course, welcome!). Through a mix of lectures, hands-on exercises, mini-case discussions and guest speakers, students will develop an understanding of the full process of data-driven marketing from problem identification to the generation of implementable solutions.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["marketing", "predictive-models", "generative-models", "customer-churn", "customer-feedback", "seo", "marketing-copy", "llms", "market-research", "data-driven", "analytics"]
  },
  {
    "title": "AI Essentials for Business",
    "course_number": "BU.520.710",
    "school": "Carey Business School",
    "units": [],
    "instructors": ["Gao, Gordon"],
    "description": "Artificial Intelligence (AI) is making substantial inroads into our everyday lives, demonstrating tremendous potential across numerous domains, including business and healthcare. This course aims to impart learners with crucial understanding of AI's core technologies, such as neural networks, deep learning, computer vision, natural language processing, and generative AI. We will also provide a succinct introduction to the burgeoning areas within AI. This course takes a hands-on, experiential learning approach, making use of the latest cloud computing platforms to provide practical understanding and application. Through this course, students will establish a robust comprehension of vital AI technologies, equipping themselves with the working knowledge required to harness these technologies in driving business growth and creating value.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["ai-fundamentals", "neural-networks", "deep-learning", "computer-vision", "nlp", "generative-ai", "cloud-computing", "hands-on", "business-value", "healthcare"]
  },
  {
    "title": "Introduction to Human-Centered AI",
    "course_number": "EN.601.694",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Yao, Yaxing"],
    "description": "Artificial intelligence (AI) has transformed nearly every aspect of modern life. Tools such as ChatGPT and Gemini have greatly expanded human capability, but they also raise critical questions about privacy, accessibility, ethics, and human agency. This course introduces the emerging field of human-centered, an approach that integrates human values, design principles, and technical understanding to ensure AI systems are useful, usable, and responsible. Through a combination of lectures, guest talks, hands-on projects, and in-class activities, students will explore key dimensions of human-centered AI: human aspects, technical aspects, human–AI interaction, special domains. In addition, the course features interactive workshops introducing tools and frameworks essential to human-centered AI practice, such as Figma, React, and the OpenAI API. Required Course Background: foundational knowledge of AI/ML concepts, programming, and human-centered design or behavioral science. Students can earn credit for at most one of 601.494/694.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Cross-credit note: at most one of 601.494/694.",
    "keywords": ["human-centered-ai", "human-ai-interaction", "design", "ethics", "privacy", "accessibility", "human-agency", "figma", "react", "openai-api", "workshops"]
  },
  {
    "title": "The Future of Work with AI Systems",
    "course_number": "EN.601.784",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Hager, Greg"],
    "description": "There are any number of predictions on how AI will impact the future of work, including a national academies study on the topic. However, the fact is that how work is impacted and how it changes depends fundamentally on both what “the work” is, the level of AI performance necessary to create an effective solution, and if or how human support is involved in the solution. The goal of this course is to 1) Explore different application areas of AI – its use in information-intensive tasks, its use in image-intensive tasks, and its use in physical world tasks; 2) Understand the system structures that are being developed to deploy AI – for example how human backup is used to support systems that require high fidelity; 3) Touch on some of the policy and regulatory structures that impact our ability to develop and deploy AI-driven solutions. Students are expected to have some background in AI.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["future-of-work", "ai-systems", "deployment", "human-in-the-loop", "high-fidelity-systems", "policy", "regulation", "information-tasks", "vision-tasks", "robotics", "workforce"]
  },
  {
    "title": "Generative AI for Entrepreneurs",
    "course_number": "EN.635.674",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Information Systems Engineering"],
    "instructors": ["Irani, Jal J"],
    "description": "The Generative AI for Entrepreneurs course is a comprehensive, hands-on practical learning experience designed for student who have interest in transitioning to become AI entrepreneurs with the knowledge and skills necessary to leverage the power of AI in their business ventures. This course focuses on the practical applications of cutting-edge AI techniques, enabling students to develop innovative products and services that stand out in the competitive business landscape and prepare them to successfully interactive with financial investors including angels, venture capitalists, family offices, and institutional investors. The course will have many guest speakers and will culminate with a Shark Tank pitch session.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["entrepreneurship", "generative-ai", "product-development", "hands-on", "startups", "investors", "venture-capital", "pitching", "business-models", "guest-speakers"]
  },
  {
    "title": "Introduction to Generative AI",
    "course_number": "EN.705.605",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Artificial Intelligence"],
    "instructors": ["Guven, Erhan", "Vu, Vy Ngoc Thao"],
    "description": "This introductory course on generative artificial intelligence (AI) offers a comprehensive overview of the foundational principles and techniques that enable machines to generate complex outputs, such as text, images, and music. Students will explore the history and evolution of generative AI, including landmark models and milestones that have shaped the field. The course will first review classical approaches such as expert systems, genetic algorithms, Markov models, and constraint satisfaction problems. This will be followed by key algorithms and models in generative AI, including but not limited to neural networks, Autoencoders, generative adversarial networks (GANs), and transformers. Ethical considerations and societal impacts of generative AI will be a critical component of the curriculum, encouraging students to think critically about issues such as bias, fairness, and privacy. Assessment will include project work, where students will demonstrate their ability to develop a generative AI application from concept to implementation. By the end of the course, students will have a solid understanding of generative AI, equipped with the skills to innovate and apply these technologies in diverse and ethically responsible ways. This section may be cross-listed with other sections in the same course.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "May be cross-listed.",
    "keywords": ["generative-ai", "text-generation", "image-generation", "music-generation", "autoencoders", "gans", "transformers", "expert-systems", "markov-models", "ethics", "bias", "privacy", "project-based"]
  },
  {
    "title": "Introduction to Agentic AI",
    "course_number": "EN.705.625",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Artificial Intelligence"],
    "instructors": ["Saeed, Amir Kashif"],
    "description": "In this course, we will dive into what it truly means to build agentic AI—systems that perceive their environment, make decisions, learn from experience, and act autonomously. We begin by exploring the core principles of intelligent agency and how these systems interact with the world around them. From there, we will examine foundational models and techniques for crafting intelligent behavior, including decision trees, utility theory, Markov decision processes, and game theory. As the course progresses, you will design both standalone agents and complex multi-agent systems, learning how they make decisions, communicate, collaborate, and compete. We will also explore the human side of AI—how to build trust, ensure explainability, and design intuitive interfaces for effective human-AI collaboration. In the final phase, we investigate the frontier of AI: generative agents powered by large language and vision models. These advanced systems do not merely react—they reflect, plan, and interact in ways that resemble human cognition. You will gain hands-on experience building and evaluating these agents using state-of-the-art frameworks. By the end of the course, you will be equipped to model, build, and evaluate intelligent agents for both simulated and real-world environments, with a solid grounding in both theory and practice.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["agentic-ai", "autonomy", "mdps", "decision-trees", "utility-theory", "game-theory", "multi-agent-systems", "communication", "trust", "explainability", "human-ai-collaboration", "generative-agents"]
  },
  {
    "title": "Using Generative Artificial Intelligence (AI) to Improve Public Health",
    "course_number": "PH.340.621",
    "school": "Bloomberg School of Public Health",
    "units": ["PH Epidemiology"],
    "instructors": ["Dowdy, David Wesley", "Klaas, Brian D"],
    "description": "Introduces students to core concepts in the utilization of generative artificial intelligence (AI) tools. Explores ethical, financial, and policy-based issues in the application of generative AI to public health. Contrasts accuracy and reach of generative AI with the potential for both misinformation and problem solving. Enables students to develop skills in utilizing generative AI tools for public health research and practice.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["public-health", "generative-ai", "policy", "ethics", "finance", "misinformation", "research", "practice", "health-communication", "decision-support"]
  },

  {
    "title": "Information Policy Strategy and Design in the Age of AI",
    "course_number": "SA.501.113",
    "school": "Nitze School of Advanced International Studies",
    "units": ["SA Technology and Innovation", "SA MASCI"],
    "instructors": ["Sedenberg, Elaine"],
    "description": "Information and digital technologies have transformed the way modern societies operate over the last 20 years and introduced unprecedented opportunities as well as thorny policy challenges such as privacy, ethics, data rights, and competition. The meteoric rise of artificial intelligence in the last year has reinvigorated many of these recurring information policy challenges, and heightened tensions between the drive for rapid innovation alongside calls for regulation. Students will develop a foundational understanding of key concepts within information policy issues and apply it to information-intensive emerging technologies including AI/Generative AI, digital platforms and social media, smart devices/Internet of Things, and AR/VR/Metaverse. Students will build technical knowledge necessary to diagnose and remedy policy issues at hand, be able to discuss the ethical tradeoffs and nuances of contested issues from multiple perspectives, and curate a toolkit of policy approaches and regulatory options available for emerging tech. Relevant current events and technological developments will be incorporated into the course throughout the semester, and students will be expected to interact with many of the technologies discussed throughout to spark class discussion and inform future practice. This course will leave students with knowledge that will allow them to feel equally comfortable traversing the boardrooms of Silicon Valley and corridors of power within Washington DC.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["information-policy", "ai-policy", "regulation", "privacy", "data-rights", "competition", "digital-platforms", "internet-of-things", "ar-vr-metaverse", "ethics", "governance", "current-events"]
  },
  {
    "title": "AI and National Security",
    "course_number": "SA.501.119",
    "school": "Nitze School of Advanced International Studies",
    "units": ["SA Technology and Innovation", "SA MASCI", "SA Security, Strategy, and Statecraft"],
    "instructors": ["Buchanan, Benjamin"],
    "description": "The course examines one of the topics most central for the future of national security policy: artificial intelligence (AI). We will begin first by examining what AI is and isn’t, and discuss how the underlying technology works. We will then proceed to survey the national security landscape and consider how AI will impact key policy and strategy decisions in the near future. Topics discussed include autonomous weapons, intelligence collection and analysis, cyber attacks, disinformation, and technology competition. We will also focus on the AI strategies of the US and China. No technical background is required for this class, though we will introduce some important ideas that are relevant to how AI works. Students will be evaluated through a key concepts quiz that assesses understanding of important ideas. They will also be assigned one final paper in which they will take a stand on a proposition regarding AI’s policy impact. In addition, class participation is a vital component of this class, as a substantial portion of each week will be oriented towards discussion.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["national-security", "autonomous-weapons", "intelligence", "cybersecurity", "disinformation", "us-china", "strategy", "policy", "technology-competition", "ai-basics"]
  },
  {
    "title": "Ghost in the Machine: The Intellectual History of AI and its Risks",
    "course_number": "SA.501.121",
    "school": "Nitze School of Advanced International Studies",
    "units": ["SA Technology and Innovation", "SA MASCI", "SA Security, Strategy, and Statecraft"],
    "instructors": ["Rid, T"],
    "description": "Ghost in the Machine traces the history of one of humanity’s most powerful and most consequential ideas: that humans could build machines that surpass themselves, in all faculties, and thus outwit our maker, ultimately cheating death and disease. This idea has become the best-funded futurist project of our time. We will investigate how mythical thinking about intelligent machines has evolved since World War II, what effects such thinking has had on the development of intelligent machinery, and how breakthroughs in neural networks, deep learning, and transformers over seventy years have shaped our capacity to foresee and manage the future of artificial—and human—intelligence. We will trace seven critical ideas: extinction, salvation, the intelligence explosion, training, black boxes, agents, and a curious vanishing act. The detailed historical reconstruction of innovation reveals how the technology actually works: students will acquire familiarity with some of the core concepts of artificial intelligence, such as neural networks, gradient descent, false peaks, vectorization, weights, backpropagation, self-attention, transformers, the scaling laws, interpretability, feature extraction, circuits, superposition, and alignment trends. Students will also gain appreciation for the key thinkers, innovators, and engineers who have shaped AI — its technology, its ideology, and its politics. No math or technical background is required. Rid will use this class as an experimental space to demo cutting edge AI-tools that enhance and accelerate the research and learning process — as they are getting updated and released.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["ai-history", "risk", "myth-and-ideology", "neural-networks", "deep-learning", "transformers", "gradient-descent", "backpropagation", "self-attention", "scaling-laws", "interpretability", "alignment", "intelligence-explosion"]
  },
  {
    "title": "Research Seminar: Critical AI: Questions and Methods",
    "course_number": "AS.145.460",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS Medicine, Science and the Humanities"],
    "instructors": ["Tatarchenko, Ksenia"],
    "description": "Borrowing its title from a new journal and an emerging, interdisciplinary field of study, this class examines artificial intelligence, and its subfield of machine learning, through the lens of the humanities and social sciences. The course focuses on the historical, cultural, ethical, and societal dimensions of AI. It combines group discussions of selected readings with individual research projects supervised by the instructor.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Research seminar (as titled).",
    "keywords": ["critical-ai", "humanities", "social-sciences", "ethics", "history", "culture", "society", "machine-learning", "research-project", "seminar", "readings"]
  },
  {
    "title": "Explainable AI Design & Human-AI Interaction",
    "course_number": "EN.601.484",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Staff"],
    "description": "This is a design course. Increasing the trustworthiness of machine learning solutions has emerged as an important research area. One approach to trustworthy machine learning is explainable and/or interpretable machine learning, which attempts to reveal the working mechanisms of a machine learning system. However, other than on-task performance, explainability is not a property of machine learning algorithms, but an affordance: a relationship between explanation model and the target users in their context. Successful development of machine learning solutions that afford explainability thus requires understanding of techniques beyond pure machine learning. In this course, we will first review the basics of machine learning and human-centered design. Then, we will introduce several techniques to explain machine learning models and/or make them interpretable, and through hands-on sessions and case studies, will investigate how these techniques affect human-AI interaction. In addition to individual homework assignments, students will work in groups to design, justify, implement, and test an explainable machine learning algorithm for a problem of their choosing.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["explainability", "interpretability", "human-ai-interaction", "human-centered-design", "trustworthy-ai", "case-studies", "affordances", "ml-design", "group-project", "evaluation"]
  },
  {
    "title": "AI for Public Health in Python",
    "course_number": "PH.140.629",
    "school": "Bloomberg School of Public Health",
    "units": ["PH Biostatistics"],
    "instructors": ["Argo, Mary Joy", "Caffo, Brian S", "Hassoon, Ahmed Abdullah", "Moghadas, Babak"],
    "description": "Presents the basics of data science using the python programming language. Teaches basic unix, version control, graphing and plotting techniques, creating interactive graphics, web app development, reproducible research tools and practices, resampling based statistics and artificial intelligence via deep learning, focusing on practical implementation specifically tied to computational tools and core fundamentals necessary for practical implementation. Culminates with a web app development project chosen by student (who will come out of this course sequence well-equipped to tackle many of the data science problems that they will see in their research).",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Instructor list included a duplicate name in the source; de-duplicated here.",
    "keywords": ["public-health", "python", "data-science", "unix", "version-control", "visualization", "interactive-graphics", "web-apps", "reproducible-research", "resampling", "deep-learning"]
  },

  {
    "title": "AI for Musicians",
    "course_number": "PY.350.821",
    "school": "The Peabody Institute",
    "units": ["PY Computer Music"],
    "instructors": ["Moore, Ted"],
    "description": "Students are introduced to the fundamentals of machine listening, data science, and machine learning by applying these techniques to musical materials. Topics include neural networks, classification, regression, dimensionality reduction, clustering, and spectral decomposition. Student work focuses on using personally-created datasets for analysis, training, and the creation of original artistic expressions.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["computer-music", "machine-listening", "machine-learning", "neural-networks", "classification", "regression", "dimensionality-reduction", "clustering", "spectral-decomposition", "creative-practice", "datasets"]
  },
  {
    "title": "Cognitive Principles of Artificial Intelligence",
    "course_number": "AS.050.251",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS Cognitive Science", "EN Computer Science"],
    "instructors": ["Hu, Jennifer"],
    "description": "The rise of artificial intelligence (AI) is one of the most powerful—and controversial—breakthroughs of our lifetime. Some say that large language models, like ChatGPT, are oracles that will render human thought obsolete. Others say that these models are “stochastic parrots” with no real understanding of the text they produce. Who is right? And what would it even mean for a machine to be able to think and use languages like humans do? This course will give students the tools to answer these questions and critically analyze AI through a grounding in cognitive science, with a focus on language. Topics will include the technical foundation of language models, human language learning, syntax, semantics, pragmatics, reasoning, creativity, and how AI use is affecting our own minds. Strongly recommended: prior course in programming and/or probability theory.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["cognitive-science", "language-models", "llms", "syntax", "semantics", "pragmatics", "reasoning", "creativity", "human-language-learning", "stochastic-parrots", "ai-and-mind"]
  },
  {
    "title": "Minds and Machines",
    "course_number": "AS.140.316",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS History of Science, Medicine, and Technology", "AS Medicine, Science and the Humanities"],
    "instructors": ["Honenberger, Phillip"],
    "description": "Is the mind identical to the brain? Is the mind (or brain) a computer? Could a computer reason, have emotions, or be morally responsible? This course examines such questions philosophically and historically. Topics include the history of AI research from 1940s to present; debates in cognitive science related to AI (computationalism, connectionism, and 4E cognition); and AI ethics.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["philosophy-of-mind", "cognitive-science", "ai-history", "computationalism", "connectionism", "4e-cognition", "ai-ethics", "brains-and-computers", "responsibility"]
  },

  {
    "title": "Human-AI Fusion",
    "course_number": "BU.330.765",
    "school": "Carey Business School",
    "units": ["BU Information Systems"],
    "instructors": ["Wang, Wei Weiguang"],
    "description": "This cutting-edge course is designed for professionals, technologists, and leaders who are eager to harness the combined power of human creativity and artificial intelligence. The course offers an in-depth exploration of how AI can augment human capabilities, enhance decision-making processes, and transform industries. Topics covered include the comparison and combination of human and AI capabilities, AI as a service to human users, augmented intelligence, brain-computer interface, human-AI teaming, autonomous intelligence, social AI, and the business of human-AI fusion. Upon completion, students will have acquired the essential knowledge and skills to develop strategies for human-AI collaboration, focusing on roles, tasks, and processes that maximize the strengths of both.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Waitlist Only (per source).",
    "keywords": ["human-ai-collaboration", "augmentation", "decision-making", "brain-computer-interface", "human-ai-teaming", "autonomous-systems", "social-ai", "strategy", "leadership", "industry-transformation"]
  },
  {
    "title": "AI-Driven Sequential Decision Making",
    "course_number": "BU.520.750",
    "school": "Carey Business School",
    "units": ["BU Quantitative Methods"],
    "instructors": ["Eshragh, Ali"],
    "description": "This course will serve as a nexus between business analytics and cutting-edge artificial intelligence (AI) methodologies, which are increasingly vital in strategic business decision-making, encompassing areas from sales forecasting and inventory optimization to revenue management and supply chain analytics. There is a strong emphasis on the art, theory, and applications of Markov decision processes (MDPs) in modeling and optimizing large-scale business analytics problems in the presence of uncertainty. While MDPs can be applied to a broad range of decision analytics problems in practice, they often encounter the curse of dimensionality, which leads to exponential growth in the size of these models. To address this challenge, state-of-the-art AI methods, reinforcement learning (RL) and deep RL, are extensively discussed as solutions to overcome the curse of dimensionality. Additionally, if time permits, the course will present further recent advancements in AI-empowered decision analytics. This course will balance theory and practical applications of AI-empowered decision analytics, making it accessible to a diverse range of students and practitioners in fields like business, economics, finance, and engineering. Each lecture is composed of three components: theory, case studies, and tools. These are designed to equip students with an understanding of the underlying art and theory of MDPs and RL, insights into real-world applications, and proficiency in Python programming. Additionally, through a final group project, students will gain hands-on experience in the entire process of predictive and prescriptive analytics in practice. The final outcomes will be showcased through presentations.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["sequential-decision-making", "mdps", "reinforcement-learning", "deep-rl", "curse-of-dimensionality", "business-analytics", "optimization", "uncertainty", "python", "prescriptive-analytics", "supply-chain"]
  },

  {
    "title": "Applications of Artificial Intelligence in Health Professions Education",
    "course_number": "ED.880.679",
    "school": "School of Education",
    "units": ["ED Advanced Studies in Education"],
    "instructors": ["Khamis, Nehal"],
    "description": "This six-week course introduces students to the transformative role of Artificial Intelligence (AI) in all aspects of health professions education. Learners will explore theoretical concepts, practical applications, and ethical considerations of AI, equipping them to critically evaluate and creatively apply AI tools in didactic and clinical curriculum design, research, and teaching.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Six-week course (per description).",
    "keywords": ["health-professions-education", "curriculum-design", "clinical-education", "ai-tools", "ethics", "teaching", "research", "evaluation", "education-technology"]
  },
  {
    "title": "The Ethics of Artificial Intelligence and Automation",
    "course_number": "EN.601.124",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Gligoric, Kristina"],
    "description": "The expansion of artificial intelligence (AI)-enabled use cases across a broad spectrum of domains has underscored the benefits and risks of AI. This course will address the various ethical considerations engineers need to engage with to build responsible and trustworthy AI-enabled autonomous systems. Topics to be covered include: values-based decision making, ethically aligned design, cultural diversity, safety, bias, AI explainability, privacy, AI regulation, the ethics of synthetic life, and the future of work. Case studies will be utilized to illustrate real-world applications. Students will apply learned material to a group research project on a topic of their choice.",
    "credits": "3.00",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["ai-ethics", "automation", "values-based-design", "safety", "bias", "explainability", "privacy", "regulation", "synthetic-life", "future-of-work", "case-studies"]
  },
  {
    "title": "Artificial Intelligence",
    "course_number": "EN.601.464",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Haque, Musad Al"],
    "description": "The course situates the study of Artificial Intelligence (AI) first in the broader context of Cognitive Science (i.e., human intelligence) and then treats in-depth principles and methods for reasoning, planning, and learning, including both conventional methods and recent deep learning approaches. The class is recommended for all scientists and engineers with a genuine curiosity about how to build an AI system (in particular, an intelligent agent) that can learn, reason about, and interact with the world and other agents. Strong programming skills and a solid mathematical foundation are expected. Students will be asked to complete both programming assignments and writing assignments. Students can only receive credit for one of 601.464/664. This section may be cross-listed with other sections in the same course.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Cross-credit note: only one of 601.464/664. May be cross-listed.",
    "keywords": ["ai", "reasoning", "planning", "learning", "intelligent-agents", "deep-learning", "cognitive-science", "programming", "math-foundations", "assignments"]
  },
  {
    "title": "Machine Social Intelligence",
    "course_number": "EN.601.773",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Shu, Tianmin"],
    "description": "No other species possesses a social intelligence quite like that of humans. Our ability to understand one another’s minds and actions, and to interact with one another in rich and complex ways, is the basis for much of our success, from governments to symphonies to the scientific enterprise. This course will discuss the principles of human social cognition, how we can use machine learning and AI models to computationally capture these principles, how these principles can help us build human-level machine social intelligence, and how social intelligence can enable the engineering of AI systems that can understand and interact with humans safely and productively in real-world settings. In this seminar course, we will read and discuss literature that cover diverse topics on social intelligence in humans and machines. These include (but are not limited to) social perception, Theory of Mind, multi-agent planning, multi-agent communication, social learning, human-AI teaming, moral judgment, and value alignment. Required Course Background: Linear Algebra, Probability and Statistics, and Calculus; 601.475/675 Machine Learning or EN.601.464/664 Artificial Intelligence or equivalent.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Prerequisites listed.",
    "keywords": ["social-intelligence", "theory-of-mind", "multi-agent-systems", "social-cognition", "human-ai-interaction", "value-alignment", "moral-judgment", "social-learning", "communication", "seminar", "ml-prereq"]
  },

  {
    "title": "Cognitive and Behavioral Foundations for Artificial Intelligence",
    "course_number": "EN.705.640",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Artificial Intelligence", "PE Robotics and Autonomous Systems"],
    "instructors": ["Lopez, Monica"],
    "description": "As a result of greater computing power and Big Data, artificial intelligence (AI) is rapidly improving for well-defined tasks and narrow intelligence. Moreover, it has entered all industries in a myriad of ways. But will AI ever have human-like general intelligence? What does humanlike general intelligence even mean? Why should we even care? This course is designed to answer these complex questions by giving students working knowledge of the underlying principles and mechanisms of human behavior and cognition, and how they may be applied to solving current and rising industry challenges. Key topics to be addressed will include vision, audition, language, learning, emotion and social cognition, creativity, and consciousness. Students will apply learned topics to a final group research project on the topic of their choice.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["cognition", "human-behavior", "general-intelligence", "vision", "audition", "language", "emotion", "social-cognition", "creativity", "consciousness", "industry-applications"]
  },
  {
    "title": "Large Language Models: Theory and Practice",
    "course_number": "EN.705.651",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Artificial Intelligence"],
    "instructors": ["Barham, Sam Alexander"],
    "description": "An apparently new breed of neural network -- the large language model (LLM) -- figures increasingly in today's news: ChatpGPT and Microsoft's new chatbot-like Bing Chat interface seem to garner headlines on the daily. This course constitutes a thorough introduction to this technology, tracing the historical threads in computational linguistics and language modeling that led to it, and exploring the design patterns that underpin its application in modern AI systems. In between, students will learn about language modeling, the attention mechanism, prompt and instruction tuning, composability, quantization, low-rank adaptation, and the wealth of software and hardware optimizations that enable LLMs to be used at scale and with acceptable latencies.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["llms", "language-modeling", "attention", "prompting", "instruction-tuning", "quantization", "lora", "low-rank-adaptation", "optimization", "deployment", "computational-linguistics"]
  },
  {
    "title": "Artificial Intelligence for Leaders",
    "course_number": "EN.705.615",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Artificial Intelligence", "PE Engineering Management"],
    "instructors": ["McCulloh, Ian"],
    "description": "This course is designed for leaders tasked with spearheading artificial intelligence (AI) efforts within their organizations. As AI technologies such as machine learning, deep learning, symbolic AI and generative AI reshape the landscape of industry and governance, understanding how to effectively integrate these tools into business strategies becomes paramount. This course offers an in-depth exploration of the critical components of AI, including data acquisition and analysis, algorithm development, the deployment of resources, labor considerations and the management of at-scale AI projects. Participants will gain a robust understanding of the foundational and advanced concepts of AI, including the workings of machine learning models, the revolutionary capabilities of transformers and large language models (LLMs), the innovative potential of generative AI, and risk mitigation with symbolic AI. The curriculum emphasizes not only the technical aspects but also the management and ethical considerations, such as bias mitigation and the development of responsible AI frameworks, ensuring leaders can make informed, ethical decisions in deploying AI technologies.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["leadership", "ai-strategy", "project-management", "data", "deployment", "transformers", "llms", "generative-ai", "symbolic-ai", "risk-mitigation", "ethics", "bias-mitigation"]
  },
  {
    "title": "Practical Skills in Using Generative Artificial Intelligence (GenAI) in Public Health",
    "course_number": "PH.340.631",
    "school": "Bloomberg School of Public Health",
    "units": ["PH Epidemiology"],
    "instructors": ["Dowdy, David Wesley", "Klaas, Brian D"],
    "description": "Provides hands-on instruction to develop practical skills in use of generative AI for public health applications. Uses worked examples and group exercises to build skills in: (a) drafting policy briefs, op-eds and persuasive prose; (b) writing statistical code; (c) data visualization; (d) developing career materials; (e) drafting grant proposals, research products, and teaching materials; (f) summarizing data for decision-makers; and (g) writing more effective interpersonal communications.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["public-health", "generative-ai", "policy-briefs", "data-visualization", "statistical-coding", "grant-writing", "summarization", "decision-support", "communication", "career-materials", "hands-on"]
  },

  {
    "title": "Practical Mathematics for AI",
    "course_number": "AS.110.204 (88)",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS Mathematics"],
    "instructors": ["Ali Yousuf, Muhammad"],
    "description": "This course provides a rigorous yet accessible introduction to the essential mathematical foundations underlying modern Artificial Intelligence (AI) and Deep Learning applications. The course emphasizes the practical application of linear algebra, probability, statistics, calculus, and optimization techniques in the design and understanding of machine learning systems. Students will explore how these core mathematical tools are used to build models for computer vision, regression, classification, clustering, and deep neural networks. Each topic is contextualized with real-world problems, Python Code, and bridging theory with implementation. The course is designed for students from diverse academic backgrounds who want to gain a solid foundation in mathematics for working with AI systems. Topics include: Vectors, matrices, and tensor operations; Calculus and gradient-based optimization for training neural networks; Probability theory and statistical inference in machine learning; Mathematical intuition behind computer vision, regression, classification, clustering, and deep neural networks with practical use cases.",
    "credits": "4.00",
    "term": "Fall 2025",
    "campus": "Homewood Campus",
    "notes": "Appears to be a specific section (88).",
    "keywords": ["linear-algebra", "probability", "statistics", "calculus", "optimization", "tensors", "gradient-based-optimization", "deep-learning", "computer-vision", "python", "math-foundations"]
  },
  {
    "title": "Philosophy and AI",
    "course_number": "AS.150.471",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS Philosophy"],
    "instructors": ["Gross, Steven"],
    "description": "This course explores philosophical issues raised by developments in Artificial Intelligence. For example, can a machine be conscious? (What is consciousness?) Who is responsible for a bad decision made by AI? What light, if any, do developments in AI shed on age-old debates about nature vs. nurture?",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["philosophy", "consciousness", "responsibility", "ai-decision-making", "nature-vs-nurture", "ethics", "mind", "agency"]
  },
  {
    "title": "The Future of Work: AI, Labor, and Migration",
    "course_number": "AS.305.135",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS Critical Study of Racism, Immigration, & Colonialism", "AS Comparative Thought and Literature", "AS History of Science, Medicine, and Technology", "AS Political Science"],
    "instructors": ["Todarello, Josh"],
    "description": "How is the so-called “AI Revolution” altering the landscape of work? This course takes up this question through the lens of underemployment, migratory labor, and diasporic communities. We will read a variety of key works on migration and imagined communities, precarity and alienation, labor, automation, and empire—as well as texts produced in the margins of globalization. In conversation with these texts, we will investigate the dynamics of diasporic communities, migration, and solidarity vis-a-vis the future of work in a global society increasingly automated by AI models such as DeepSeek, ChatGPT, and Qwen 2.5, and the entities that own them. Through a variety of writing assignments and presentations, students engage issues such as race, class, gender, the border, citizenship, and community as they exist for diasporic and migratory workers. This course explores themes relevant to students of Critical Diaspora Studies, as well as the history of science and technology, political science and political economy, international studies, literature, film, and sociology. Readings may include works by Ruha Benjamin, Audre Lorde, Harry Braverman, Benedict Anderson, David Harvey, Edward Said, Mary L. Gray, Octavia Butler, and Ngũgĩ wa Thiong’o.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["future-of-work", "labor", "migration", "diaspora", "automation", "precarity", "political-economy", "race", "gender", "borders", "solidarity", "globalization"]
  },
  {
    "title": "SOUL: The Algorithmic Eye: AI takes on Hollywood",
    "course_number": "AS.360.111",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS Interdepartmental"],
    "instructors": ["Saad, Alaa Amr"],
    "description": "Film is a creative medium and an art. It is a fictive, real, and profound way of knowing and making real worlds. It is a storyline and life mirrored in image, sound, light, and movement. It reflects our being in the world and our imaginations of what could be. In this course, students will explore the influence of the move to digital technologies on the textures of filmmaking. How do we watch and read movies like Ex-Machina, The Matrix, or Her that deal with speculative realities of AI before the emergence of AI on the world stage? We will explore questions about using artificial intelligence (AI) technologies within filmmaking, focusing on how the ‘digital’ represents ‘realities’ of gender, memory, race, class, and environmental degradation. Moving between forms of scholarly work on digital media and AI-based films, students will become familiar with how AI opens a new imagination of creative representations and forecloses others.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["film", "hollywood", "digital-media", "ai-in-film", "speculative-fiction", "gender", "memory", "race", "class", "environment", "media-analysis"]
  },
  {
    "title": "Production for Creative Technology: AI, Neuroscience & Performance",
    "course_number": "AS.455.645",
    "school": "Krieger School of Arts and Sciences Advanced Academic Programs",
    "units": ["AAP Film and Media"],
    "instructors": ["Sack, Graham"],
    "description": "This course, offered in conjunction with a Nexus Research Grant sponsored by the Hopkins Bloomberg Center, explores how neuroscience, AI, wearable biometrics, and brain-computer interface (BCI) technology can transform immersive storytelling, interactive media, and live performance. Students will have the opportunity to collaborate closely with an active production that will be in development, rehearsal, and performance at JHU during the 2025-2026 academic year. Initial course meetings will focus on creative research, speculative design, and world-building exercises, utilizing Stanislaw Lem’s iconic science fiction novel Solaris as a source text and springboard for collective imagining. We will juxtapose Lem’s novel with iconic film adaptations and critical theory about the climate crisis, environmental and synthetic intelligence, planetary-scale computation, and the ontology of “hyperobjects.” Mid-semester, students will work hands-on with neurotechnology and AI, including EEG headsets, AI tools, and interactive performance platforms. The course culminates in classroom-based, student-led demo performances integrating AI, BCI technologies, and experimental theater techniques. Guest artists and field trips will further enrich the experience. Prerequisite: students must have taken at least one ISET course although exceptions will be granted on a case by case basis based on the student's level of experience.",
    "credits": "",
    "term": "2025-2026 academic year (project context)",
    "campus": "",
    "notes": "Prerequisite mentioned (ISET).",
    "keywords": ["creative-technology", "neuroscience", "bci", "wearables", "biometrics", "interactive-media", "performance", "eeg", "ai-tools", "world-building", "speculative-design", "hyperobjects"]
  },
  {
    "title": "AI Technology, Innovation, and Policy",
    "course_number": "AS.470.738",
    "school": "Krieger School of Arts and Sciences Advanced Academic Programs",
    "units": ["AAP Government"],
    "instructors": ["Waggoner, Philip"],
    "description": "This course is an introduction to the tools used to create chat and analytical artificial intelligence (AI) applications including the ethical considerations associated with AI including bias, transparency, fairness, accuracy and the methods used to measure and assess the results produced by AI. The different forms of AI in the public sector are evaluated using the AI products currently in use at the federal, state, and local level. The application of AI for diverse policy areas including policing, disaster mitigation, and foreign policy and citizens’ responses to interactions with AI in service provision are also covered, along with current and emerging policy guidelines for public sector AI.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["public-sector", "ai-applications", "chatbots", "analytics", "policy", "bias", "fairness", "transparency", "evaluation", "policing", "disaster-mitigation", "foreign-policy"]
  },
  {
    "title": "AI Essentials for Business",
    "course_number": "BU.520.710",
    "school": "Carey Business School",
    "units": [],
    "instructors": ["Irani, Jal J"],
    "description": "Artificial Intelligence (AI) is making substantial inroads into our everyday lives, demonstrating tremendous potential across numerous domains, including business and healthcare. This course aims to impart learners with crucial understanding of AI's core technologies, such as neural networks, deep learning, computer vision, natural language processing, and generative AI. We will also provide a succinct introduction to the burgeoning areas within AI. This course takes a hands-on, experiential learning approach, making use of the latest cloud computing platforms to provide practical understanding and application. Through this course, students will establish a robust comprehension of vital AI technologies, equipping themselves with the working knowledge required to harness these technologies in driving business growth and creating value.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Duplicate title/course number appears with different instructor in source; kept as separate entry.",
    "keywords": ["ai-fundamentals", "neural-networks", "deep-learning", "computer-vision", "nlp", "generative-ai", "cloud-computing", "hands-on", "business-value", "healthcare"]
  },
  {
    "title": "AI in Education",
    "course_number": "ED.893.653",
    "school": "School of Education",
    "units": ["ED Innovative Teaching & Leadership"],
    "instructors": ["Hassan, Zia"],
    "description": "Artificial intelligence (AI) is transforming education, influencing how we learn, teach, and—perhaps—think about understanding knowledge itself. This course critically examines AI as both a tool and a mirror, reflecting human cognition, creativity, ethics, and systemic biases. Through hands-on experimentation, critical analysis, and applied projects, students will explore AI’s potential to enrich and expand educational goals and practices while questioning its limitations and potential dangers. Designed for a broad range of educational professionals, the course balances theoretical inquiry with practical skill development. Students will engage with AI tools, analyze their impact, and apply them in meaningful ways to their professional contexts. The course is structured around five interconnected themes: (1) AI, Cognition, and Learning; (2) AI as Co-Intelligence and Thought Partner; (3) Ethics, Bias, and AI Governance; (4) AI and the Purposes of Education; (5) Policy, Design, and Future Directions: Designing responsible AI frameworks for educational settings.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["education", "ai-tools", "learning", "cognition", "co-intelligence", "ethics", "bias", "governance", "policy", "design", "professional-practice"]
  },
  {
    "title": "FYS: Explaining AI Through Games",
    "course_number": "EN.501.145",
    "school": "Whiting School of Engineering",
    "units": ["EN First Year Seminars"],
    "instructors": ["Murray, Kenton W"],
    "description": "This course will look at Artificial Intelligence and the algorithms and technology behind it through the lens of games. We will discuss how popular games such as Wordle, Crossword Puzzles, and Cards Against Humanity offer really detailed insights into the core workings of AI – from how they are trained, to what happens when they are deployed to users in the wild. While we will get into cutting-edge algorithms and engineering advances, no prior technical knowledge or programming skills are required. At the end of the semester, students will be able to understand and debate engineering decisions and principles underlying all of the fundamental technological aspects of Modern AI systems. Students are expected to come to class prepared to discuss assigned readings and there will be a class project to build an AI Bot to play the popular TV show game Wheel of Fortune.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["first-year-seminar", "games", "ai-explanation", "algorithms", "training", "deployment", "wordle", "nlp", "project", "bot-building", "discussion-based"]
  },
  {
    "title": "AI Safety, Alignment, & Governance",
    "course_number": "EN.601.469",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Hadfield, Gillian"],
    "description": "This course will focus on the alignment and governance challenges posed by advanced frontier/general purpose AI models: why these models may behave in ways that pose significant risk to human welfare and what technical and governance approaches might mitigate these risks. We’ll begin the course studying general results from alignment and governance in human normative systems such as markets, politics, norms and laws. We’ll pay special attention to risks arising from agentic AI. We’ll then look at current technical and position papers in various topics in AI safety and alignment. Topics could include: RLHF, constitutional AI, red-teaming, safety evaluation methods, red lines, jail-breaking, prompt injection, over-optimization, and open-source debates. We’ll conclude with discussion of regulatory frameworks such as regulatory markets, registration of frontier models, international governance organizations, registration of AI agents and legal personhood for AI agents. This is a paper-reading class.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Paper-reading class (per description).",
    "keywords": ["ai-safety", "alignment", "governance", "agentic-ai", "rlhf", "constitutional-ai", "red-teaming", "evals", "jailbreaking", "prompt-injection", "regulatory-frameworks", "frontier-models"]
  },
  {
    "title": "Advanced Machine Learning: Machine Learning for Trustworthy AI",
    "course_number": "EN.601.787",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Liu, Anqi"],
    "description": "This course teaches advanced machine learning methods for the design, implementation, and deployment of trustworthy AI systems. The topics we will cover include but are not limit to different types of robust learning methods, fair learning methods, safe learning methods, and research frontiers in transparency, interpretability, privacy, sustainability, AI safety and ethics. Students will learn the state-of-the-art methods in lectures, understand the recent advances by critiquing research articles, and apply/innovate new machine learning methods in an application. There will be homework assignments and a course project.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["advanced-ml", "trustworthy-ai", "robustness", "fairness", "safety", "transparency", "interpretability", "privacy", "sustainability", "ai-ethics", "research-frontiers"]
  },
  {
    "title": "Applied Generative AI",
    "course_number": "EN.705.608",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Artificial Intelligence"],
    "instructors": ["Cruickshank, Iain", "McCulloh, Ian", "Rodriguez, Pedro Angel"],
    "description": "This course provides a comprehensive exploration of generative artificial intelligence (AI) and its practical applications in solving complex business challenges. This course combines theoretical instruction with hands-on experience, equipping participants with the skills to design, develop, and deploy Generative AI-driven solutions. Topics include prompt engineering, natural language processing (NLP), generative AI workflows, fine-tuning large language models (LLMs), agentic AI development, secure AI practices, and the evaluation of AI solutions. Participants will also gain insight into ethical AI practices to ensure responsible and fair use of this technology. The curriculum includes two hands-on projects and analysis of real-world case studies. This program is designed for technology professionals, data analysts, engineers, consultants, technical managers, and STEM graduates seeking to enhance their expertise in generative AI. A foundational understanding of programming and data analysis is recommended. Participants will develop proficiency in using tools such as Python, VS Code, and various libraries. They will also learn techniques for retrieval-augmented generation (RAG), quick fine-tuning with vector databases, and use of open-source LLMs for proprietary applications. This course prepares graduates to apply generative AI to a wide range of applications, develop and train generative models, apply these techniques to create content, evaluate ethical implications, and analyze the impact of AI on various industries and society.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["generative-ai", "prompt-engineering", "nlp", "fine-tuning", "llms", "agentic-ai", "secure-ai", "evaluation", "rag", "vector-databases", "open-source-llms", "hands-on-projects"]
  },
  {
    "title": "Neuromarketing AI",
    "course_number": "EN.705.618",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Artificial Intelligence"],
    "instructors": ["Morin, Christophe"],
    "description": "In today’s rapidly evolving marketplace, the key to effective leadership is understanding the intersection of science, technology, and consumer behavior. Neuromarketing AI: The Future of Persuasion and Consumer Insights, is a pioneering course designed specifically for leaders who seek to harness the latest advancements in neuroscience and artificial intelligence to transform their marketing strategies and decision-making processes. This course merges groundbreaking brain science with AI-driven techniques, giving participants a unique opportunity to master the science of persuasion and its real-world applications. Participants will explore how the human brain processes decisions, learn how to apply neuromarketing principles, and leverage AI to predict consumer behavior and personalize messaging at scale. With a curriculum built on the renowned Persuasion Code model, this program will empower participants to revolutionize how they communicate with customers, employees, and stakeholders.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["neuromarketing", "consumer-behavior", "neuroscience", "persuasion", "personalization", "prediction", "marketing-strategy", "decision-making", "ai-in-marketing", "leadership"]
  },
  {
    "title": "HEROIC: Data, AI, and Society: Case Studies in Technology Ethics and Social Impact",
    "course_number": "EN.500.312",
    "school": "Whiting School of Engineering",
    "units": ["EN General Engineering"],
    "instructors": ["Nixon, Kristen Ivy"],
    "description": "Data science is intertwined with some of the most pressing problems in society, including environmental sustainability, public health, social justice, and the preservation of democracy. Each week of this course will feature a different case study, including modeling for high-stakes decision making, the impact of social media algorithms on political discourse and mental health, the promise and perils of large language models, and the future impact of artificial general intelligence. Students will wrestle with ethical questions, practice responsible decision-making, do a deep dive on a case study of their interest, and reflect on their own values and ambitions as an engineer.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["data-science", "social-impact", "technology-ethics", "case-studies", "high-stakes-decisions", "social-media", "mental-health", "llms", "agi", "sustainability", "social-justice", "democracy"]
  },
  {
    "title": "FYS: The Drama of Artificial Intelligence",
    "course_number": "AS.001.253",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS First Year Seminars", "AS Cognitive Science", "AS Psychological & Brain Sciences", "AS Theatre Arts & Studies"],
    "instructors": ["Flombaum, Jonathan", "Gruenhut, Johanna"],
    "description": "From the rise of machine consciousness to the ethics of automation, artificial intelligence has captured the human imagination. This First-Year Seminar explores how playwrights and theater artists engage with AI as a dramatic subject, a creative tool, and a lens for examining the human condition. Through an interdisciplinary approach, and co-taught by faculty in Psychological and Brain Sciences and Theatre, students will analyze plays and performances that grapple with the hopes and anxieties surrounding AI. Works such as Karel Čapek’s R.U.R. (which introduced the word “robot”), Jordan Harrison’s Marjorie Prime, Jennifer Haley’s The Nether, and Nick Payne’s Constellations will serve as key texts alongside contemporary plays such as Julia Cho’s The Language, Rolin Jone’s The Intelligent Design of Jenny Chow, The Effect by Lucy Prebble, and Photograph 51 by Anna Ziegler. We will also discuss experimental performances that integrate AI technologies.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["theatre", "drama", "ai-in-culture", "machine-consciousness", "automation-ethics", "plays", "performance", "robot", "human-condition", "interdisciplinary", "creative-tool"]
  },
  {
    "title": "Ethics and Technology",
    "course_number": "AS.150.332",
    "school": "Krieger School of Arts and Sciences",
    "units": ["AS Philosophy"],
    "instructors": ["Wonderly, Monique Lisa"],
    "description": "In this course, we will examine philosophical debates concerning the moral permissibility of developing, distributing, and/or using certain controversial technologies. Candidate technologies for consideration include, but are not limited to, nootropics (smart drugs), moral bioenhancement, so-called “ultraviolent” video games, memory-alteration technologies, the development of drugs that aim to create, sustain, or eliminate love, and AI intended to function as therapists, romantic interests, or interactive representations of deceased loved ones",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["ethics", "technology", "philosophy", "nootropics", "bioenhancement", "memory-alteration", "ai-therapists", "human-relationships", "controversial-tech", "moral-permissibility"]
  },

  {
    "title": "Data Science: Artificial Intelligence",
    "course_number": "BU.920.624",
    "school": "Carey Business School",
    "units": ["BU MBA"],
    "instructors": ["Dai, Tinglong"],
    "description": "Since its inception in 1950s, Artificial Intelligence (AI) has been shaped by the rise and fall of various competing ideas and techniques emerging from a myriad of disciplines, including computer science, economics, ethics, linguistics, mathematics, operations research, philosophy, psychology, and statistics. Since 2012, deep learning has taken center stage in AI and expanded the landscape of AI to include applications spanning virtually all industries and sectors. This course introduces key concepts of AI, including its mathematical, computational, and economic foundations, and how to manage and lead businesses in the age of AI. Students will learn how to develop concrete AI applications that transform structured and unstructured data to tools with potential of generating business and human value. Students will develop a concrete understanding of AI strategy in a variety of scenarios, including health, operations and supply chain management, marketing, and marketplace design. Students will also develop AI leadership skills that synthesize human and non-human intelligence, with limitation of AI in mind, including, for example, how AI can amplify or mitigate human biases.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["data-science", "ai", "deep-learning", "business-strategy", "operations", "supply-chain", "marketing", "marketplace-design", "leadership", "economics", "bias", "foundations"]
  },
  {
    "title": "Artificial Intelligence and Business of Health",
    "course_number": "BU.920.724",
    "school": "Carey Business School",
    "units": ["BU MBA"],
    "instructors": ["Dai, Tinglong"],
    "description": "Artificial intelligence is not the future of healthcare. It is already a reality in medicine, and its importance in improving healthcare delivery is expected to grow substantially in future decades. As of June 2024, 950 AI-powered medical devices have been cleared for clinical use by the U.S. Food and Drug Administration. The recent boom in generative AI has further fueled enthusiasm for medical AI, presenting a rare opportunity to address challenges like aging populations, declining productivity, rising costs, and disparities in access to care. This course explores the intersection of AI and the business of health, introducing key AI concepts, including its mathematical and computational foundations, economic forces, and its impact on healthcare. Students will learn how to develop predictive and generative AI applications that transform structured and unstructured healthcare data into tools that enhance patient outcomes, streamline operations, and create value in the health sector. The course will cover AI strategies in various healthcare contexts, including patient care, medical research, healthcare operations, and public health supply chains. A key focus will be on the science of scaling medical AI, integrating AI into clinical workflows to improve productivity, access, and equity in healthcare. The course will also address the importance of sustainable reimbursement models for medical AI, exploring different paths AI creators can take towards reimbursement and the roles of various stakeholders in this process. Additionally, students will develop AI leadership skills that synthesize human and non-human intelligence, with an understanding of AI’s inner workings and limitations, including how AI can reinforce or mitigate human biases in healthcare. By the end of the course, students will be equipped to lead the integration of AI into healthcare systems, ensuring that AI’s benefits are broadly and appropriately realized, supported by sustainable financial models.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["healthcare", "medical-ai", "predictive-models", "generative-ai", "clinical-workflows", "scaling", "equity", "reimbursement", "operations", "public-health-supply-chains", "bias", "leadership"]
  },
  {
    "title": "FYS: Computational Reasoning",
    "course_number": "EN.501.152",
    "school": "Whiting School of Engineering",
    "units": ["EN First Year Seminars"],
    "instructors": [],
    "description": "This seminar is a hands-on survey of the fundamental concepts of computer science, spanning everything from the art of “thinking slowly” to the cutting edge of machine learning and AI alignment. We’ll learn to design clear, step-by-step problem-solving strategies, represent them in flowcharts, and see how encoding information in binary enables circuits to perform logic and math. We'll learn how structuring information makes it possible to build data processing machines and we'll learn how those machines recognize patterns, follow instructions, seek goals, keep secrets, see, and learn. You’ll complete the seminar with a synoptic view of the conceptual terrain of computer science and a set of critical thinking skills that dovetail with those cultivated in the humanities and social sciences. Class sessions will focus on lively discussions, hands-on exercises, debates, and collaborative problem-solving during our meetings. No prior coding experience is required; although you’ll encounter some code, learning to program is not a primary goal of the course and is not part of the assessment.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["computational-reasoning", "computer-science-foundations", "problem-solving", "flowcharts", "binary", "logic", "patterns", "algorithms", "security", "machine-learning", "ai-alignment", "hands-on"]
  },
  {
    "title": "Artificial Intelligence and Machine Learning (AI-ML) for Global Health",
    "course_number": "EN.580.449",
    "school": "Whiting School of Engineering",
    "units": ["EN Biomedical Engineering"],
    "instructors": ["Acharya, Soumya", "Soenksen Martinez, Luis Ruben"],
    "description": "The field of Artificial Intelligence has seen major breakthroughs in recent years, offering unprecedented possibilities in addressing major global health challenges, particularly in health equity and access. This foundational course in AI for Global Health aims to provide students with the theoretical basis and practical skills needed to apply machine learning techniques to healthcare innovations for global public health problems. The course does not require prior background in machine learning or global public health. It takes a unique approach by teaching foundational machine learning topics using case studies and real-life data from global health innovation projects across Africa, South Asia, and Latin America. Students will learn machine learning topics alongside weekly case studies involving datasets from projects on Malaria, Maternal Health, Neonatal Health, Primary Health Care, Cancer, and more. The course covers topics from basic machine learning to advanced techniques like convolutional neural networks, generative AI, and time series/sequence data. Labs and mini-projects will involve applying these methods to real datasets, culminating in a final challenge project based on a real-life multi-country implementation in East Africa. Prerequisites: Programming knowledge in a high-level language such as Python.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Prerequisite: programming (e.g., Python).",
    "keywords": ["global-health", "health-equity", "machine-learning", "case-studies", "africa", "south-asia", "latin-america", "cnns", "generative-ai", "time-series", "public-health", "python"]
  },
  {
    "title": "Data Science for the Technical Leader",
    "course_number": "EN.595.758",
    "school": "Whiting School of Engineering for Professionals",
    "units": ["PE Engineering Management", "PE Technical Management"],
    "instructors": ["Dinmore, Matt Daniel", "Kramer, Mike"],
    "description": "The course provides an immersive introduction to data science for scientists and engineers who are in technical leadership positions and recognize the need to lead their organizations into a data-driven future. Through lectures, hands-on exercises, and project assignments, the course illustrates the fundamental concepts of data science and introduces the students to the skills required to apply the tools and techniques through the data science process to problems in support of fulfilling mission objectives. The course exposes the students to data management, data science tools and techniques, the basics of Artificial Intelligence (AI) and Machine Learning (ML), creating and delivering data-driven solutions, evaluating their efficacy, policy, and ethical considerations. Familiarity with desktop operating systems and software is required for this course. While students will perform hands-on coding exercises, only basic familiarity with software coding concepts is required.",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "",
    "keywords": ["data-science", "technical-leadership", "data-management", "ml", "ai-basics", "hands-on", "project-assignments", "evaluation", "policy", "ethics", "mission-objectives"]
  },
  {
    "title": "The Ethics of Artificial Intelligence and Automation",
    "course_number": "EN.601.124",
    "school": "Whiting School of Engineering",
    "units": ["EN Computer Science"],
    "instructors": ["Lopez, Monica"],
    "description": "The expansion of artificial intelligence (AI)-enabled use cases across a broad spectrum of domains has underscored the benefits and risks of AI. This course will address the various ethical considerations engineers need to engage with to build responsible and trustworthy AI-enabled autonomous systems. Topics to be covered include: values-based decision making, ethically aligned design, cultural diversity, safety, bias, AI explainability, privacy, AI regulation, the ethics of synthetic life, and the future of work. Case studies will be utilized to illustrate real-world applications. Students will apply learned material to a group research project on a topic of their choice. The ePortfolio tag(s) on this course signify that there are one or more assignments offered in the course that provide students with the opportunity to be assessed for proficiency in completion of the relevant ePortfolio requirement(s).",
    "credits": "",
    "term": "",
    "campus": "",
    "notes": "Duplicate course number appears with different instructor; source also mentions ePortfolio assignments.",
    "keywords": ["ai-ethics", "automation", "values-based-design", "safety", "bias", "explainability", "privacy", "regulation", "synthetic-life", "future-of-work", "case-studies", "eportfolio"]
  }
,

{
  "course_number": "AS.300.615",
  "school": "KSAS",
  "title": "How to Pay Attention and Why",
  "units": [""],
  "instructors": [""],
  "description": "It is not uncommon to hear two closely related concerns in discussions of our present social predicament. On the one hand is the sense that humanity is facing a series of unprecedented threats, including climate change, the proliferation of nuclear weapons, the rise of AI, and growing economic and social inequalities. These challenges and the solutions they require are extraordinarily complex. On the other hand, there is increasing concern that our capacity to pay attention to such complex issues is being eroded by a culture that values and foments distraction and superficiality. The internet, social media, gaming, dopamine addiction, commodification, and the entertainment industry have all been said to be responsible for a reductive political discourse interested more in ratings and outrage than substantive debate and solutions. This course examines the merits of these concerns and asks what alternatives may be available. In the first part, we will look at academic and popular accounts of our attention economy and the dangers it entails. In the second part we will examine one of the most powerful tools the humanities offer against superficiality and distraction: the practice of close reading as a way of attending to the world.",
  "credits": "",
  "term": "",
  "campus": "",
  "notes": "",
  "keywords": ["attention","social media", "critique"]
}
]